version: '1'
services:
  fastp:
    image: biocontainers/fastp:v0.20.1_cv1
    volumes:
      - .:/data
    command: fastp --in1 /data/input.fastq --out1 /data/output.fastq
    platform: linux/amd64

  bowtie2:
    image: biocontainers/bowtie2:v2.4.1_cv1
    depends_on:
      - fastp
    volumes:
      - .:/data
    command: bowtie2 -x /data/index -1 /data/output.fastq -2 /data/output_r2.fastq -S /data/output.sam
    platform: linux/amd64

  freebayes:
    image: biocontainers/freebayes:v1.2.0-2-deb_cv1
    depends_on:
      - bowtie2
    volumes:
      - .:/data
    command: sh -c "freebayes -f /data/reference.fa /data/input.bam > /data/output.vcf"
    platform: linux/amd64
